import 'package:flutter/animation.dart';

class AppColors {
  AppColors._();
  static const Color white = Color(0xffFFFFFF);
  static const Color authSpansColor = Color(0xff68AEFF);
  static const Color backgroundColor = Color(0xff181B20);
  static const Color primaryColor = Color(0xff2563EB);
  static const Color cardColor = Color(0xff1F2933);
  static const Color dashboardContainerBackground = Color(0xff1B1D21);
  static const Color dashboardContainerBorder = Color(0xff3F4246);
  static const Color lightBlueColor = Color(0xff68AEFF);
  static const Color greyColor = Color(0xffBDBDBD);
  static const Color labelTextColor = Color(0xffBDBDBD);
  static const Color cardColor1 = Color.fromRGBO(214, 214, 214, 0.14);
  static const Color cardColor2 = Color.fromRGBO(112, 112, 112, 0.14);
  static const Color yellowColor = Color(0xffFFAE77);
  static const Color greenColor = Color(0xff6DD695);
  static const Color redColor = Color(0xffFE6D73);
  static const Color darkGreyColor = Color(0xff292E36);
  static const Color gradientColor1 = Color(0xffD6D6D6);
  static const Color gradientColor2 = Color(0xff707070);
  static const Color flyoutBgColor = Color(0xff292E36);
  static const Color userDetailIconColor = Color(0xffBDBDBD);
  static const Color borderColor = Color(0x993F4246);
  static const Color chartColor1 = Color(0xFF60A5FA);
  static const Color chartColor2 = Color(0xFFFB7185);
  static const Color chartColor3 = Color(0xFFFBBF24);
  static const Color chartColor4 = Color(0xFF3B82F6);
  static const Color whiteOpacity60 = Color.fromRGBO(255, 255, 255, 0.3);
  static const Color whiteOpacity40 = Color.fromRGBO(255, 255, 255, 0.4);
  static const Color likePink = Color(0xffF20E8E);
  static const Color dividerLight = Color(0x1AFFFFFF);
  static const Color buttonGradientStart = Color.fromRGBO(255, 255, 255, 0.18);
  static const Color buttonGradientEnd = Color.fromRGBO(255, 255, 255, 0.06);
  static const Color cardShadowFeed = Color(0x1A000000);
  static const Color profileImgBgColor = Color(0xff35383C);
  static const Color eventCardBorderColor = Color(0x3F42464D);
  static const Color eventCardBgColor = Color(0x001d2024);
  static const Color eventCardIconBgColor = Color(0x135FFF54);
  static const Color transparentColor = Color(0x00000000);
  static const Color eventCardIconBgColor2 = Color(0x135FFFA4);
  static const Color redColor2 = Color(0xffFE6D73);
  static const Color blue400 = Color(0xff68AEFF);
  static const Color externalEventColor = Color(0xffFFDC13);
  static const Color activeStatusTextColor = Color(0xff6DD695);
  static const Color activeStatusBgColor = Color(0x1A6DD695);
  static const Color inactiveStatusTextColor = Color(0xffFE6D73);
  static const Color inactiveStatusBgColor = Color(0xff34282C);
}
