import '../common/constant/app_strings.dart';

const Map<String, String> en_US = {
  // App
  AppStrings.appName: 'Samsung Community Admin',
  'sCommunity': 'S Community',
  'welcome': 'Welcome to our',

  // Common Actions
  'logout': 'Logout',
  'wantLogout': 'Are you sure you want to logout?',
  'editProfile': 'Edit Profile',
  'yes': 'Yes',
  'no': 'No',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'editPost': 'Edit Post',
  'update': 'Update',
  'search': 'Search',
  'filter': 'Filter',
  'select': 'Select',
  'next': 'Next',
  'back': 'Back',
  'submit': 'Submit',
  'action': 'Action',
  'editing': 'Editing',
  'deletionTxt': 'Deletion',

  // Menu Items
  'menu': 'Menu',
  'language': 'Language',
  'settings': 'Settings',
  'profile': 'Profile',
  'dashboard': 'Dashboard',
  'vodPodcasts': 'VOD & Podcasts',
  'academy': 'Academy',
  'monthlyTasks': 'Monthly Tasks',
  'community': 'Community',
  'events': 'Events',
  'pointStore': 'Point Store',
  'users': 'Users',
  'weeklyRiddle': 'The weekly riddle',

  // weekly riddle
  'uploadANewPuzzle': 'Upload a new puzzle',
  'taskType': 'Task Type',
  'taskStartDate': 'Task Start Date',
  'taskCompletionDateR': 'Task Completion Date',
  'isRequired': 'is required',
  'weeklyRiddleCreatedSuccessfully': 'Weekly riddle created successfully',
  'weeklyRiddleCreationFailed': 'Weekly riddle creation failed',
  'missionNameRequired': 'Mission name is required',
  'descriptionRequired': 'Description is required',
  'startDateRequired': 'Start date is required',
  'endDateRequired': 'End date is required',
  'invalidDateFormat': 'Invalid date format. Use dd-MM-yyyy',
  'missionEndTimeRequired': 'Mission end time is required',
  'totalPointsRequired': 'Total points required',
  'totalPointsToWinRequired': 'Total points to earn is required',
  'missionImageRequired': 'File is required',
  'correctAnswer': 'Correct answer',
  'addOption': 'Add Option',
  'option': 'Option',
  'solutionType': 'Solution Type',
  'noWeeklyRiddleFound': 'No weekly riddle found',
  'weeklyRiddleDeletedSuccessfully': 'Weekly riddle deleted successfully',
  'nameOfRiddle': 'Name of riddle',
  'typeOfPuzzle': 'Type of puzzle',
  'areYouSureYouWantToDeleteThisRiddle':
      'Are you sure you want to delete this riddle?',
  'weeklyRiddleUpdatedSuccessfully': 'Weekly riddle updated successfully',
  'weeklyRiddleUpdateFailed': 'Weekly riddle update failed',
  'vodPodcastType': 'VOD & Podcasts Type',
  'downloadToExcelFile': 'Download to Excel file',
  'correctAnswerRequired': 'Correct answer is required',
  'viewSubmissions': 'View Submissions',
  'nameOfMissionForRiddle': 'Name of mission for riddle',
  'totalAnswersForMission': 'Total answers for mission',
  'wrongAnswer': 'Wrong answer',
  'totalAnswersToTheTask': 'Total answers to the task',

  // Languages
  'english': 'English',
  'hebrew': 'Hebrew',

  // Chat
  'chat': 'Chat',

  // Dashboard
  'totalUsers': 'Total users',
  'totalLessons': 'Total Lessons',
  'totalTasks': 'Total tasks',
  'totalEvents': 'Total events',
  'totalPoints': 'Total Points',
  'totalPosts': 'Posts',
  'totalParticipants': 'Total participants',
  'statistics': 'Statistics',
  'goodAfternoon': 'Good afternoon',
  'may': 'May',
  'newUsers': 'New users',
  'viewAllUsers': 'View all users',
  'reviewOfOperations': 'Review of operations',
  'zoomWorkshops': 'Zoom workshops',
  'systemActivity':
      'Below is a brief summary of the system activity and the updates that have been made recently.',

  // Time Ranges
  'last6MonthsRangeTitle': 'Last 6 months',
  'last12MonthsRangeTitle': 'Last 12 months',
  'last30DaysRangeTitle': 'Last 30 days',
  'last6MonthsRange': 'Last 6 months',
  'last12MonthsRange': 'Last 12 months',
  'last30DaysRange': 'Last 30 days',
  'weeklyRangeTitle': 'Weekly',
  'monthlyRangeTitle': 'Monthly',
  'yearlyRangeTitle': 'Yearly',
  'weeklyRange': 'Weekly',
  'monthlyRange': 'Monthly',
  'yearlyRange': 'Yearly',

  // User Management
  'userName': 'User name',
  'registrationDate': 'Registration date',
  'gender': 'Gender',
  'city': 'City',
  'points': 'Points',
  'socialLink': 'Social link',
  'status': 'Status',
  'awaitingApproval': 'Awaiting Approval',
  'happiness': 'Happiness',
  'rejected': 'Rejected',
  'userConfirmation': 'User confirmation',
  'userRejection': 'User rejection',
  'blockingAUser': 'Blocking a user',

  // VOD & Podcasts
  'manageAndReviewTheLatestVideoOnDemandAndPodcastContentInTheCommunityDescription':
      'Manage and review the latest video-on-demand and podcast content in the community.',
  'uploadANewFile': 'Upload a new File',
  'contentType': 'Content Type',
  'uploadAFile': 'Upload a file',
  'uploadAPicture': 'Upload a picture',
  'uploadABackgroundImage': 'Upload a background image',
  'selectTheTypeOfFileYouWant': 'Select the type of file you want to upload.',
  'createAFile': 'Create a file',
  'fileType': 'File type',
  'fileName': 'File name',
  'creationDate': 'Creation date',
  'podcast': 'Podcast',
  'noFileSelected': 'No file selected',
  'fileCreatedSuccessfully': 'File created successfully',
  // Events
  'createEvent': 'A New Event',
  'eventDate': 'Event Date',
  'validity': 'Validity',
  'creditCost': 'Credit Cost',
  'costPoints': 'Cost in Points',
  'backgroundImage': 'Background Image',
  'uploadFile': 'Upload File',
  'explanatoryVideoOptional': 'Explanatory video (optional)',
  'createAnEvent': 'Create an Event',
  'orders': 'Orders',
  'eventUpdatedSuccessfully': 'Event updated successfully',
  'eventCreatedSuccessfully': 'Event created successfully',
  'failedToCreateEvent': 'Failed to create event',
  'editEvent': 'Edit Event',
  'updateEvent': 'Update Event',
  'imageRequired': 'Image required',
  'videoRequired': 'Video required',
  'imageError': 'Image error',
  'videoError': 'Video error',
  'exampleJpgPng': 'Example: .jpg, .png',
  'exampleMp4': 'Example: .mp4',
  'viewOrders': 'View Orders',
  'eventDateIsRequired': 'Event date is required',
  'endDateIsRequired': 'End date is required',
  'validityIsRequired': 'Validity is required',
  'creditCostIsRequired': 'Credit cost is required',
  'descriptionIsRequired': 'Description is required',
  'createANewEvent': 'Create a new event',
  'theDateOfTheEvent': 'The date of the event',
  'costInPointsOptional': 'Cost in Points (optional)',
  'answerStatusWrong': 'Answered incorrectly',
  'answerStatusCorrect': 'Answer correctly',
  'answerStatusPending': 'Review Pending',
  'sharePostAlsoInTheCommunityFeed': 'Share post also in the community feed',
  // form
  'video': 'Video',
  'pointsBalance': 'Points Balance',
  'fullName': 'Full Name',
  'pending': 'Pending',
  'approved': 'Approved',
  'rejectedUser': 'Rejected',
  'suspendedUser': 'Suspended',
  'titleIsRequired': 'Title is required',
  'uploadANewFileDescription': 'Upload a new file to the community.',
  'pleaseSelectAFileToUpload': 'Please select a file to upload',

  // store
  'storeTitle': 'Store',
  'products': 'Products',
  'createProduct': 'Create Product',
  'newProduct': 'New Product',
  'costInPointsProd': 'Cost in Points',
  'quantity': 'Quantity',
  'updateProduct': 'Update Product',
  'validityProduct': 'Validity',
  'productUpdatedSuccessfully': 'Product Updated Successfully',
  'productDeletedSuccessfully': 'Product Deleted Successfully',
  'titleProduct': 'Title',
  'descriptionProduct': 'Description',
  'backgroundImageProduct': 'Background Image',
  'costInPointsProduct': 'Cost in Points',
  'costInPointsProductOptional': 'Cost in Points (optional)',
  'amountIsRequired': 'Amount is required',
  'costIsRequired': 'Cost is required',
  'costInPointsIsRequired': 'Cost in Points is required',
  'areYouSureYouWantToDeleteThisProduct':
      'Are You Sure YouWant To Delete This Product',
  'productCreatedSuccessfully': 'Product created successfully',

  // academy
  'academyTitle': 'Academy',
  'monthlyTasksTitle': 'Monthly Tasks',
  'addAnotherField': 'Add another field',

  'newUpload': 'New Upload',
  'academyDescription':
      'Below is a brief summary of the system\'s activity and the updates that have been made recently.',
  'vod': 'VOD',
  'skillChallenge': 'Skill Challenge',
  'zoomLiveWorkshop': 'Zoom Live Workshop',
  'workshopDate': 'Workshop Date',
  'selectDate': 'Select Date',
  'startTime': 'Start Time',
  'selectStartTime': 'Select Start Time',
  'endTime': 'End Time',
  'selectEndTime': 'Select End Time',
  'costOfParticipationInPoints': 'Cost of participation in points (optional)',
  'audioFileIsRequired': 'Audio file is required',
  'backgroundImageIsRequired': 'Background image is required',
  'invalidUrl': 'Invalid URL',
  'creditCardParticipationCost':
      'Cost of participation in credit card (optional)',
  'workshopName': 'The name of the workshop',
  'zoomLink': 'Zoom link',
  'create': 'Create',
  'nameOfTask': 'The name of the task',
  'nameOfVideo': 'The name of the video',
  'nameOfWorkshop': 'The name of the workshop',
  // community
  'uploadANewPost': 'Upload a new post',
  'communityDescription':
      'Below is a brief summary of the system\'s activity and the updates that have been made recently.',
  'datePublished': 'Published on',
  'others': 'others',
  'commentAdded': 'Comment Added',
  'likedBy': 'liked by',
  'viewAllComments': 'View all comments',
  'viewAll': 'View all',
  'areYouSureYouWantToDeleteThisComment':
      'Are you sure you want to delete this comment?',
  'readMore': 'Read more',
  'readLess': 'Read less',
  'addComment': 'Add comment',
  // Users List
  'usersList': 'Users',
  'usersListDescription':
      'Below is a brief summary of the system\'s activity and the updates that have been made recently.',
  'dateOfBirth': 'Date of Birth',
  'userGender': 'Gender',
  'userCity': 'City',
  'userPoints': 'Points',
  'userSocialLink': 'Social Link',
  'userStatus': 'Status',
  'userBlockingAUser': 'Blocking a User',
  'userAddingPoints': 'Adding Points',
  'blockUser': 'Blocking a User',
  'viewProfile': 'View Profile',
  'accountDetails': 'Account Details',
  'accountStatus': 'Account Status',
  'active': 'Active',
  'phoneModelType': 'Phone Model Type',
  'profession': 'Profession',
  'mobileNumber': 'Mobile Number',
  'bio': 'Bio',
  'zoomParticipation': 'Zoom participation',
  'watchingVideos': 'Watching videos',
  'academicTasks': 'Academic tasks',
  'tasks': 'Tasks',
  'selectTheAmountOfPointsYouWouldLikeToSendToMaiBozo':
      'Select the amount of points you would like to send to Mai Bozo.',
  'send': 'Send',
  'reapproveUser': 'Reapprove User',
  'unblockUser': 'Unblock User',
  'suspended': 'Suspended',
  'createdAt': 'Created At',
  'dob': 'DOB',
  'residence': 'Residence',

  // Settings
  'whenAUserIsBlocked':
      'When a user is blocked, their access to the application is revoked and they cannot perform any actions.',
  'withTheReleaseOfTheBlock':
      'With the release of the block, the user can return and use the application as usual',
  'blockedUsers': 'Blocked users',
  'unblock': 'Unblock',
  'user1': 'User 1',
  'user2': 'User 2',
  'user3': 'User 3',
  'user4': 'User 4',
  'user5': 'User 5',
  'blockedDate': 'Blocked date: 09/12/25',
  'newApplicationJoinRequest': 'New application join request',
  'applicationJoinRequestDate': 'Application join request date: 09/12/25',
  // Form Fields
  'start': 'Start',
  'end': 'End',
  'title': 'Title',
  'description': 'Description',
  'typeHere': 'Type here...',
  'name': 'Name',
  'date': 'Date',
  'dates': 'Dates',
  'size': 'Size',
  'hours': 'Hours',
  'numberOfPoints': 'Number of points',
  'amountOfPoints': 'Amount of points',
  'deleteConfirmation': 'Are you sure you want to delete',

  // Edit Profile
  'editProfileDescription': 'You can edit your profile picture or your name',
  'undoChanges': 'Undo Changes',
  'saveChanges': 'Save Changes',
  'addProfilePicture': 'Add Profile Picture',

  // Notifications
  'alerts': 'Alerts',
  'noAlerts': 'No alerts',
  'noAlertsDescription': 'No alerts found',
  'applicationJoinRequest': 'Application join request',
  // Sort & Filter
  'sortBy': 'Sort by:',
  'filterBy': 'Filter by:',
  'all': 'All',
  'everything': 'Everything',
  'externalEvents': 'External Events',
  'internalEvents': 'Internal Events',
  'import': 'Import',
  'imported': 'Imported',
  'selectAnEventToImport': 'Select an event to import',

  // Messages & Descriptions
  'youHaventUploadedTheWeeklyPuzzle':
      'You haven\'t uploaded the weekly puzzle yet. ',
  'delaysRegisteringForZoomWorkshopsParticipatingInAcademicAssignmentsAndTheWeeklyPuzzle':
      'Delays registering for Zoom workshops, participating in academic assignments, and the weekly puzzle',

  // Validation Messages
  'emailCantBeEmpty': 'Email can\'t be empty!',
  'pleaseEnterAValidEmailAddress': 'Please enter a valid email address',
  'phoneNoCantBeEmpty': 'Phone Number can\'t be empty',
  'pleaseEnterAValidPhoneNumber': 'Please enter a valid Phone Number',
  'cantBeEmpty': 'can\'t be empty',
  'passwordCantBeEmpty': 'Password can\'t be empty',
  'passwordMustContainWarning':
      'Password should be at least 8 characters and must contain one uppercase, one lowercase, one numeric and one special character',
  'confirmPasswordCantBeEmpty': 'Confirm Password can\'t be empty!',
  'confirmPasswordDoesntMatch': 'Confirm Password doesn\'t match',
  'descriptionShouldHaveAtLeast20Words':
      'Description should have at least 20 words',
  'fileIsRequired': 'File is required',
  'fileSizeExceeds49MB': 'File too large (max 49MB)',
  'thumbnailIsRequired': 'Thumbnail is required',
  'firstNameIsRequired': 'First name is required',
  'lastNameIsRequired': 'Last name is required',
  'pointsRequired': 'Points required',

  // Status Messages
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'info': 'Information',
  'loading': 'Loading...',
  'noData': 'No data available',
  'somethingWentWrong': 'Something went wrong',

  // Auth
  'login': 'Login',
  'email': 'Email',
  'password': 'Password',
  'forgotPassword': 'Forgot Password?',
  'rememberMe': 'Remember Me',

  'noAccountYet': 'No account yet?',
  'createAccount': 'Create an account here',
  'alreadyHaveAnAccount': 'Already have an account?',
  'sendVerificationCode': 'Send Verification Code',
  'verificationCode': 'Verification Code',
  'enterVerificationCode': 'Enter verification code',
  'resendVerificationCode': 'Resend Verification Code',
  'confirmation': 'Confirmation',
  // 'fullName': 'Full Name',
  'enterFullName': 'Enter your full name',
  'firstName': 'First Name',
  'enterFirstName': 'Enter your first name',
  'lastName': 'Last Name',
  'enterLastName': 'Enter your last name',
  'enterEmail': 'Enter your email',
  'companyName': 'Company Name',
  'enterCompanyName': 'Enter your company name',
  'continue': 'Continue',
  'uploadAPuzzle': 'Upload a puzzle',
  'enrollment': 'Enrollment',

  // Validation Messages
  'mobileNumberRequired': 'Mobile number is required',
  'invalidPhoneNumber': 'Invalid phone number. Must be at least 10 digits',
  'checking': 'Checking...',
  'generatingOtp': 'Generating OTP...',
  'otpSent': 'OTP sent. Resend in',
  'seconds': 'seconds',
  'verifying': 'Verifying...',
  'submitting': 'Submitting...',
  'fullNameRequired': 'Full name is required',
  'fullNameTooShort': 'Full name is too short',
  'firstNameRequired': 'First name is required',
  'firstNameTooShort': 'First name is too short',
  'lastNameRequired': 'Last name is required',
  'lastNameTooShort': 'Last name is too short',
  'emailRequired': 'Email is required',
  'invalidEmail': 'Invalid email address',
  'companyNameRequired': 'Company name is required',
  'userNotFound': 'User not found',
  'userAlreadySignedUp': 'User already signed up',
  'waitForApproval': 'Please wait for approval',
  'otpIncorrect': 'Incorrect verification code',
  'otpExpired': 'Verification code has expired',
  'userNotAdmin': 'This account is not an admin account',
  'userNotFoundPleaseSignUp': 'User not found. Please sign up first.',
  'accountPendingApproval': 'Your account is pending approval from the admin.',
  'failedToGenerateVerificationCode': 'Failed to generate verification code',
  'failedToResendVerificationCode': 'Failed to resend verification code',
  'failedToCreateAdminAccount': 'Failed to create admin account',
  'genericErrorTryAgain': 'An error occurred. Please try again.',
  'otpVerificationFailed': 'OTP verification failed',
  'errorWhileResendingCode': 'An error occurred while resending code',
  'createANewPost': 'Create a new post',
  'systemActivityDescription': 'System activity description',
  'noFilesFound': 'No Files Found',
  'noPostsFound': 'No Posts Found',
  'noAcademyFound': '''No Academy's Found''',
  'failedToDeleteContent': 'Failed to delete content',
  'contentDeletedSuccessfully': 'Content deleted successfully',
  'confirmDeletion': 'Confirm Deletion',
  'areYouSureYouWantToDeleteThisPost':
      'Are you sure you want to delete this post?',
  'areYouSureYouWantToCancelThisRegistration':
      'Are you sure you want to cancel this registration?',
  'vodName': 'Video name',
  'totalPointsToWin': 'Total Points to Earn',
  'totalPointsToWin(optional)': 'Total Points to Earn (Optional)',
  'fileSubmissionTask': 'File submission task',
  'taskCompletionDate': 'Task End Date',
  'missionEndTime': 'Task End Time',
  'missionName': 'Task name',
  'costOfParticipationInCredit(optional)':
      'Cost of participation in credit (Optional)',
  'nameOfOrder': 'Name of order',
  'orderDate': 'Order Date',
  'address': 'Address',
  'zipCode': 'Zip Code',
  'noOrdersFound': 'No Orders Found',
  'uploadAudioFile': 'Upload Audio File',
  'fileAlreadyUploaded': 'File Already Uploaded',
  'detailsAboutTheEvent': 'Details about the event',
  'maxTickets': 'Max Tickets',
  'maxTicketsIsRequired': 'Max tickets is required',
  'setToActive': 'Set to Active',
  'setToInactive': 'Set to Inactive',
  'pullEventsFromEventer': 'Pull events from Eventer',

  // Promotions
  'promotions': 'Promotions',
  'createPromotion': 'Create Promotion',
  'updatePromotion': 'Update Promotion',
  'editPromotion': 'Edit Promotion',
  'thisPromotion': 'this promotion',
  'titleRequired': 'Title is required',
  'titleMaxLengthExceeded': 'Title cannot exceed 50 characters',
  'backgroundImageRequired': 'Background image is required',
  'failedToCreatePromotion': 'Failed to create promotion',
  'failedToUpdatePromotion': 'Failed to update promotion',
  'failedToDeletePromotion': 'Failed to delete promotion',
  'frequency': 'Frequency',
  'daily': 'Daily',
  'oneTime': 'One Time',
  'setInterval': 'Set interval',
  'selectInterval': 'Select Interval',
  'interval': 'Interval',
  'days': 'Days',
  'day': 'Day',
  'hour': 'Hour',
  'minutes': 'Minutes',
  'minute': 'Minute',
  'intervalRequired': 'Interval is required',
  'allFieldsAreRequired': 'All fields are required',
  'zoomLinkIsRequired': 'Zoom link is required',
  'pleaseEnterAValidURL': 'Please enter a valid URL',
  'workshopDateIsRequired': 'Workshop date is required',
  'startTimeIsRequired': 'Start time is required',
  'endTimeIsRequired': 'End time is required',
  'nameOfWorkshopIsRequired': 'Workshop name is required',
  'taskCompletionDateIsRequired': 'Task end date is required',
  'academyVODCreatedSuccessfully': 'Academy VOD created successfully',
  'failedToCreateVOD': 'Failed to create VOD',
  'missionChallengeCreatedSuccessfully':
      'Mission Challenge created successfully',
  'option1CannotBeEmpty': 'Option 1 cannot be empty',
  'option2CannotBeEmpty': 'Option 2 cannot be empty',
  'option3CannotBeEmpty': 'Option 3 cannot be empty',
  'option4CannotBeEmpty': 'Option 4 cannot be empty',
  'option5CannotBeEmpty': 'Option 5 cannot be empty',
  'option6CannotBeEmpty': 'Option 6 cannot be empty',
  'option7CannotBeEmpty': 'Option 7 cannot be empty',
  'option8CannotBeEmpty': 'Option 8 cannot be empty',
  'option9CannotBeEmpty': 'Option 9 cannot be empty',
  'option10CannotBeEmpty': 'Option 10 cannot be empty',
  'correctAnswerIsRequired': 'Correct answer is required',
  'taskStartDateIsRequired': 'Task start date is required',
  'missionNameIsRequired': 'Mission name is required',
  'zoomWorkshopCreatedSuccessfully': 'Zoom workshop created successfully',
  'failedToCreateZoomWorkshop': 'Failed to create Zoom workshop',
  'vodNameIsRequired': 'VOD name is required',
  'videoFileIsRequired': 'Video file is required',
  'invalidPoints': 'Invalid points',
  'missionEndTimeIsRequired': 'Mission end time is required',
  'editThisPost': 'Edit this post',
};
