import '../common/constant/app_strings.dart';

const Map<String, String> he_IL = {
  // App
  AppStrings.appName: 'Samsung Community Admin',
  'sCommunity': 'S Community',
  'welcome': 'ברוכים הבאים ל',

  // Common Actions
  'logout': 'התנתק',
  'wantLogout': 'האם אתה בטוח שברצונך להתנתק?',
  'editProfile': 'ערוך פרופיל',
  'yes': 'כן',
  'no': 'לא',
  'save': 'שמור',
  'cancel': 'ביטול',
  'delete': 'מחק',
  'edit': 'ערוך',
  'search': 'חיפוש',
  'filter': 'סנן',
  'select': 'בחר',
  'next': 'הבא',
  'back': 'חזור',
  'submit': 'שלח',
  'action': 'פעולה',
  'editing': 'עריכה',
  'deletionTxt': 'מחיקה',
  'zoomParticipation': ' участие בסדנאות זום',
  'watchingVideos': 'צפייה בווידאו',
  'academicTasks': 'מטלות אקדמית',

  // Menu Items
  'menu': 'תפריט',
  'language': 'שפה',
  'settings': 'הגדרות',
  'profile': 'פרופיל',
  'dashboard': 'לוח בקרה',
  'vodPodcasts': 'VOD ופודקאסטים',
  'academy': 'אקדמיה',
  'monthlyTasks': 'משימות חודשיות',
  'community': 'קהילה',
  'events': 'אירועים',
  'pointStore': 'חנות נקודות',
  'users': 'משתמשים',
  'weeklyRiddle': 'החידה השבועית',

  // weeklyRiddle
  'uploadANewPuzzle': 'העלה חידה חדשה',
  'taskType': 'סוג משימה',
  'taskStartDate': 'תאריך תחילת משימה',
  'taskCompletionDateR': 'תאריך סיום משימה',
  'weeklyRiddleCreatedSuccessfully': 'החידה została נשמה בהצלחה',
  'weeklyRiddleCreationFailed': 'החידה נכשלה בהצלחה',
  'missionNameRequired': 'שם המשימה הוא שדה חובה',
  'descriptionRequired': 'תיאור הוא שדה חובה',
  'startDateRequired': 'תאריך התחלה הוא שדה חובה',
  'endDateRequired': 'תאריך סיום הוא שדה חובה',
  'invalidDateFormat': 'פורמט תאריך לא תקין. השתמש ב-dd-MM-yyyy',
  'missionEndTimeRequired': 'שעת סיום המשימה היא שדה חובה',
  'totalPointsRequired': 'סך הנקודות הוא שדה חובה',
  'missionImageRequired': 'תמונת משימה היא שדה חובה',
  'correctAnswer': 'תשובה נכונה',
  'addOption': 'הוסף אפשרות',
  'option': 'אפשרות',
  'solutionType': 'סוג פתרון',
  'noWeeklyRiddleFound': 'לא נמצאו חידות שבועיות',
  'weeklyRiddleDeletedSuccessfully': 'החידה נמחקה בהצלחה',
  'nameOfRiddle': 'שם החידה',
  'typeOfPuzzle': 'סוג חידה',
  'areYouSureYouWantToDeleteThisRiddle': 'האם אתה בטוח שברצונך למחוק את החידה?',
  'weeklyRiddleUpdatedSuccessfully': 'החידה עודכנה בהצלחה',
  'weeklyRiddleUpdateFailed': 'החידה נכשלה בהצלחה',
  'vodPodcastType': 'סוג וידאו/פודקאסט',
  'downloadToExcelFile': 'הורדה לקובץ אקסל',
  'correctAnswerRequired': 'תשובה נכונה הוא שדה חובה',
  'viewSubmissions': 'הצגת התרחיש',
  'nameOfMissionForRiddle': 'שם המשימה לרום איפסום',
  'totalAnswersForMission': 'סה”כ תשובות למשימה',
  'wrongAnswer': 'ענה לא נכון',
  'totalAnswersToTheTask': 'סה”כ תשובות למשימה',

  // Languages
  'english': 'אנגלית',
  'hebrew': 'עברית',

  // Chat
  'chat': 'צאט',

  // Dashboard
  'totalUsers': 'סך המשתמשים',
  'totalLessons': 'סך השיעורים',
  'totalTasks': 'סך המשימות',
  'totalEvents': 'סך האירועים',
  'totalPoints': 'סך הנקודות',
  'totalPosts': 'פוסטים',
  'totalParticipants': 'סך המשתתפים',
  'statistics': 'סטטיסטיקה',
  'goodAfternoon': 'אחר צהריים טובים',
  'may': 'מאי',
  'newUsers': 'משתמשים חדשים',
  'viewAllUsers': 'צפה בכל המשתמשים',
  'reviewOfOperations': 'סקירת פעולות',
  'zoomWorkshops': 'סדנאות זום',
  'systemActivity':
      'להלן סיכום קצר של פעילות המערכת והעדכונים שבוצעו בתקופה האחרונה.',

  // Time Ranges
  'last6MonthsRangeTitle': '6 חודשים אחרונים',
  'last12MonthsRangeTitle': '12 חודשים אחרונים',
  'last30DaysRangeTitle': '30 ימים אחרונים',
  'last6MonthsRange': '6 חודשים אחרונים',
  'last12MonthsRange': '12 חודשים אחרונים',
  'last30DaysRange': '30 ימים אחרונים',
  'weeklyRangeTitle': 'שבועי',
  'monthlyRangeTitle': 'חודשי',
  'yearlyRangeTitle': 'שנתי',
  'weeklyRange': 'שבועי',
  'monthlyRange': 'חודשי',
  'yearlyRange': 'שנתי',

  // User Management
  'userName': 'שם משתמש',
  'registrationDate': 'תאריך רישום',
  'gender': 'מגדר',
  'city': 'עיר',
  'points': 'נקודות',
  'socialLink': 'קישור חברתי',
  'status': 'סטָטוּס',
  'awaitingApproval': 'ממתין לאישור',
  'happiness': 'אושר',
  'rejected': 'נדחה',
  'userConfirmation': 'אישור משתמש',
  'userRejection': 'דחיית משתמש',
  'blockingAUser': 'חסימת משתמש',

  // Settings
  'whenAUserIsBlocked':
      'כאשר משתמש נחסם, נשללת ממנו הגישה לאפליקציה והוא אינו יכול לבצע פעולות כלשהן.',
  'withTheReleaseOfTheBlock':
      'עם שחרור החסימה, המשתמש יכול לחזור ולהשתמש באפליקציה כרגיל',
  'blockedUsers': 'משתמשים חסומים',
  'unblock': 'בטל חסימה',
  'user1': 'משתמש 1',
  'user2': 'משתמש 2',
  'user3': 'משתמש 3',
  'user4': 'משתמש 4',
  'user5': 'משתמש 5',
  'blockedDate': 'תאריך חסימה: 09/12/25',
  'newApplicationJoinRequest': 'בקשת הצטרפות לאפליקציה חדשה',
  'applicationJoinRequestDate': 'תאריך בקשה: 09/12/25',

  // VOD & Podcasts
  'manageAndReviewTheLatestVideoOnDemandAndPodcastContentInTheCommunityDescription':
      'נהל וסקור את תוכן הווידאו והפודקאסט העדכני ביותר בקהילה.',
  'uploadANewFile': 'העלה קובץ חדש',
  'uploadAFile': 'העלה קובץ',
  'uploadAPicture': 'העלה תמונה',
  'uploadABackgroundImage': 'העלה תמונת רקע',
  'selectTheTypeOfFileYouWant': 'בחר את סוג הקובץ שברצונך להעלות.',
  'createAFile': 'צור קובץ',
  'fileType': 'סוג קובץ',
  'fileName': 'שם קובץ',
  'creationDate': 'תאריך יצירה',
  'podcast': 'פודקאסט',
  'noFileSelected': 'אין קובץ נבחר',
  'fileCreatedSuccessfully': 'קובץ נוצר בהצלחה',
  'uploadANewFileDescription': 'העלה קובץ חדש לקהילה.',

  // Events
  'createEvent': 'אירוע חדש',
  'eventDate': 'תאריך אירוע',
  'validity': 'תקופת תפוגה',
  'creditCost': 'עלות באשראי',
  'costPoints': 'עלות בנקודות',
  'backgroundImage': 'תמונת רקע',
  'uploadFile': 'העלה קובץ',
  'explanatoryVideoOptional': 'ווידאו מסביר (אופציונלי)',
  'createAnEvent': 'צור אירוע',
  'orders': 'הזמנות',
  'eventCreatedSuccessfully': 'אירוע נוצר בהצלחה',
  'failedToCreateEvent': 'فشل ביצירת אירוע',
  'editEvent': 'עריכת אירוע',
  'updateEvent': 'עדכון אירוע',
  'eventUpdatedSuccessfully': 'אירוע עודכן בהצלחה',
  'failedToUpdateEvent': 'فشل בעדכון אירוע',
  'imageRequired': 'האם אתה בטוח שברצונך להעלות תמונה?',
  'videoRequired': 'האם אתה בטוח שברצונך להעלות וידאו?',
  'imageError': 'האם אתה בטוח שברצונך להעלות תמונה?',
  'videoError': 'האם אתה בטוח שברצונך להעלות וידאו?',
  'exampleJpgPng': 'مثال: .jpg, .png',
  'exampleMp4': 'مثال: .mp4',
  'amount': 'כמות',
  'viewOrders': 'הצג הזמנות',
  'eventDateIsRequired': 'תאריך אירוע הוא שדה חובה',
  'endDateIsRequired': 'תאריך סיום הוא שדה חובה',
  'validityIsRequired': 'תקופת תפוגה הוא שדה חובה',
  'creditCostIsRequired': 'עלות באשראי הוא שדה חובה',
  'costInPointsIsRequired': 'עלות בנקודות הוא שדה חובה',
  'descriptionIsRequired': 'תיאור הוא שדה חובה',
  'createANewEvent': 'צור אירוע חדש',
  'theDateOfTheEvent': 'תאריך האירוע',
  'answerStatusWrong': 'ענה לא נכון',
  'answerStatusCorrect': 'ענה נכון',
  'answerStatusPending': 'ממתין לסקירה',
  'sharePostAlsoInTheCommunityFeed': 'שתף פוסט גם בפיד הקהילה',
  'detailsAboutTheEvent': 'פרטים על האירוע',
  'maxTickets': 'כמות כרטיסים מקסימלית',
  'maxTicketsIsRequired': 'כמות כרטיסים מקסימלית היא שדה חובה',
  'setToActive': 'הגדר לפעיל',
  'setToInactive': 'הגדר ללא פעיל',
  'pullEventsFromEventer': 'משיכת אירועים מ-Eventer',

  // form
  'video': 'ווידאו',
  'pointsBalance': 'נקודות בריאות',
  'fullName': 'שם מלא',
  'pending': 'ממתין',
  'approved': 'אושר',
  // 'rejected': 'דחו',
  'rejectedUser': 'דחו',
  'suspendedUser': 'חסום',
  'titleIsRequired': 'כותרת היא שדה חובה',
  'pleaseSelectAFileToUpload': 'אנא בחר קובץ להעלאה',

  // Users List
  'usersList': 'משתמשים',
  'usersListDescription':
      'להלן סיכום קצר של פעילות המערכת והעדכונים שבוצעו בתקופה האחרונה.',
  'dateOfBirth': 'תאריך לידה',
  'userGender': 'מגדר',
  'userCity': 'עיר',
  'userPoints': 'נקודות',
  'userSocialLink': 'קישור חברתי',
  'userStatus': 'סטָטוּס',
  'userBlockingAUser': 'חסימת משתמש',
  'userAddingPoints': 'הוספת נקודות',
  'blockUser': 'חסימת משתמש',
  'viewProfile': 'הצג פרופיל',
  'accountDetails': 'פרטי חשבון',
  'accountStatus': 'סטָטוּס',
  'active': 'פעיל',
  'phoneModelType': 'סוג מודל טלפון',
  'profession': 'מקצוע',
  'mobileNumber': 'מספר טלפון',
  'bio': 'ביוגרפיה',
  'tasks': 'מטלות',
  'selectTheAmountOfPointsYouWouldLikeToSendToMaiBozo':
      'בחר את כמות הנקודות שברצונך לשלוח למשתמש מאי בוזו.',
  'send': 'שלח',
  'reapproveUser': 'אישור משתמש',
  'unblockUser': 'חסימת משתמש',
  'suspended': 'חסום',
  'createdAt': 'נוצר ב',
  'dob': 'DOB',
  'residence': 'Residence',

  // academy
  'academyTitle': 'אֲקָדֶמִיָה',
  'monthlyTasksTitle': 'משימות חודשיות',
  'addAnotherField': 'הוסף שדה נוספ',
  'newUpload': 'העלה קובץ חדש',
  'costOfParticipationInCreditOptional': 'עלות השתתפות באשראי (אופציונלי)',
  'academyDescription':
      'להלן סיכום קצר של פעילות המערכת והעדכונים שבוצעו לאחרונה.',
  'vod': 'ווידאו',
  'skillChallenge': 'משימת עיקרון',
  'zoomLiveWorkshop': 'סדנה זום חיים',
  'workshopDate': 'תאריך סדנה',
  'selectDate': 'בחר תאריך',
  'startTime': 'שעת התחלה',
  'selectStartTime': 'בחר שעת התחלה',
  'endTime': 'שעת סיום',
  'selectEndTime': 'בחר שעת סיום',
  'audioFileIsRequired': 'קובץ שמע הוא שדה חובה',
  'invalidUrl': 'קישור שגוי',
  'costOfParticipationInPoints': 'עלות השתתפות בנקודות (אופציונלי)',
  'nameOfOrder': 'שם ההזמנה',
  'orderDate': 'תאריך הזמנה',
  'address': 'כתובת',
  'zipCode': 'מיקוד',
  'noOrdersFound': 'לא נמצאו הזמנות',
  'creditCardParticipationCost': 'עלות השתתפות באשראי (אופציונלי)',
  'nameOfTask': 'שם המשימה שלך',
  'nameOfVideo': 'שם הסרטון שלך',
  'nameOfWorkshop': 'שם הסדנה שלך',
  // community
  'uploadANewPost': 'העלה פוסט חדש',
  'communityDescription':
      'להלן סיכום קצר של פעילות המערכת והעדכונים שבוצעו לאחרונה.',
  'workshopName': 'שם הסדנה שלך',
  'zoomLink': 'קישור זום',
  'create': 'צור',
  'datePublished': 'פורסם ב',
  'commentAdded': 'הערה נוספה',
  'others': 'אחרים',
  'likedBy': 'מועדף על ידי',
  'viewAllComments': 'צפה בכל התגובות',
  'viewAll': 'צפה בכל',
  'readMore': 'קרא עוד',
  'readLess': 'קרא פחות',
  'addComment': 'הוסף תגובה',
  'areYouSureYouWantToDeleteThisComment':
      'האם אתה בטוח שברצונך למחוק תגובה זו?',
  'noFilesFound': 'אין קבצים נמצאים',
  'failedToDeleteContent': 'יצירת קובץ נכשלה',
  'contentDeletedSuccessfully': 'קובץ נוצר בהצלחה',
  'confirmDeletion': 'אישור מחיקה',
  'areYouSureYouWantToDeleteThisPost': 'האם אתה בטוח שברצונך למחוק פוסט זה?',
  'areYouSureYouWantToCancelThisRegistration':
      'האם אתה בטוח שברצונך לבטל את הרישום הזה?',

  // store
  'products': ' מוצרים',
  'createProduct': 'צור מוצר',
  'newProduct': 'منتج חדש',
  'costInPointsProd': 'עלות בנקודות',
  'updateProduct': 'עדכן מוצר',
  'productUpdatedSuccessfully': 'המוצר עודכן בהצלחה',
  'productDeletedSuccessfully': 'המוצר נמחק בהצלחה',
  'quantity': 'כמות',
  'validityProduct': 'תוקף',
  'titleProduct': 'כותרת',
  'descriptionProduct': 'תיאור',
  'backgroundImageProduct': 'תמונת רקע',
  'backgroundImageIsRequired': 'תמונת רקע היא שדה חובה',
  'amountIsRequired': 'כמות היא שדה חובה',
  'costIsRequired': 'עלות היא שדה חובה',
  'productCreatedSuccessfully': 'מוצר נוצר בהצלחה',
  'contentType': 'סוג התוכן',
  // Form Fields
  'start': 'התחלה',
  'end': 'סיום',
  'title': 'כותרת',
  'description': 'תיאור',
  'typeHere': 'הקלד כאן...',
  'name': 'שם',
  'date': 'תאריך',
  'dates': 'תאריכים',
  'size': 'גודל',
  'hours': 'שעות',
  'numberOfPoints': 'מספר נקודות',
  'amountOfPoints': 'כמות נקודות',
  'areYouSureYouWantToDeleteThisProduct': 'האם אתה בטוח שברצונך למחוק מוצר זה',
  'deleteConfirmation': 'האם אתה בטוח שברצונך למחוק',

  // Notifications
  'alerts': 'אירעו עדכונים',
  'noAlerts': 'אין עדכונים',
  'noAlertsDescription': 'אין עדכונים נמצאים',
  'applicationJoinRequest': 'בקשת הצטרפות לאפליקציה',

  // Edit Profile
  'editProfileDescription': 'תוכל לערוך את תמונת הפרופיל שלך או את השם שלך',
  'undoChanges': 'ביטול שינויים',
  'saveChanges': 'שמירת שינויים',
  'addProfilePicture': 'הוסף תמונת פרופיל',

  // Sort & Filter
  'sortBy': 'מיין לפי:',
  'filterBy': 'סינון לפי:',
  'all': 'הכל',
  'everything': 'הכל',
  'externalEvents': 'אירועים חיצוניים',
  'internalEvents': 'אירועים פנימיים',
  'import': 'ייבוא',
  'imported': 'מיובא',
  'selectAnEventToImport': 'בחר אירוע לייבוא',

  // Messages & Descriptions
  'youHaventUploadedTheWeeklyPuzzle': 'עדיין לא העלת את החידה השבועית. ',
  'delaysRegisteringForZoomWorkshopsParticipatingInAcademicAssignmentsAndTheWeeklyPuzzle':
      'עיכובים ברישום לסדנאות זום, השתתפות במטלות אקדמיות והחידה השבועית',

  // Validation Messages
  'emailCantBeEmpty': 'אימייל לא יכול להיות ריק!',
  'costOfParticipationInCredit(optional)': 'עלות השתתפות באשראי (אופציונלי)',
  'pleaseEnterAValidEmailAddress': 'אנא הזן כתובת אימייל תקינה',
  'phoneNoCantBeEmpty': 'מספר טלפון לא יכול להיות ריק',
  'pleaseEnterAValidPhoneNumber': 'אנא הזן מספר טלפון תקין',
  'cantBeEmpty': 'לא יכול להיות ריק',
  'passwordCantBeEmpty': 'סיסמה לא יכולה להיות ריקה',
  'passwordMustContainWarning':
      'הסיסמה חייבת להכיל לפחות 8 תווים וחייבת להכיל אות גדולה אחת, אות קטנה אחת, מספר אחד ותו מיוחד אחד',
  'confirmPasswordCantBeEmpty': 'אישור סיסמה לא יכול להיות ריק!',
  'confirmPasswordDoesntMatch': 'אישור הסיסמה אינו תואם',
  'descriptionShouldHaveAtLeast20Words': 'תיאור חייב להכיל לפחות 20 תווים',
  'fileIsRequired': 'קובץ הוא שדה חובה',
  'fileSizeExceeds49MB': 'קובץ גדול מדי (מקסימום 49MB)',
  'thumbnailIsRequired': 'תמונה הוא שדה חובה',
  'fileAlreadyUploaded': 'קובץ כבר נטען',
  'taskCompletionDate': 'תאריך סיום המשימה',
  'missionEndTime': 'שעת סיום המשימה',

  // Status Messages
  'success': 'הצלחה',
  'error': 'שגיאה',
  'warning': 'אזהרה',
  'info': 'מידע',
  'loading': 'טוען...',
  'noData': 'אין מידע זמין',
  'somethingWentWrong': 'משהו השתבש',

  // Auth
  'login': 'התחבר',
  'email': 'אימייל',
  'password': 'סיסמה',
  'forgotPassword': 'שכחת סיסמה?',
  'rememberMe': 'זכור אותי',

  'noAccountYet': 'אין לך חשבון עדיין?',
  'createAccount': 'צור חשבון כאן',
  'alreadyHaveAnAccount': 'כבר יש לך חשבון?',
  'sendVerificationCode': 'שלח קוד אימות',
  'verificationCode': 'קוד אימות',
  'enterVerificationCode': 'הזן קוד אימות',
  'resendVerificationCode': 'שלח קוד אימות מחדש',
  'confirmation': 'אישור',
  'noTasksSubmittedYet': 'אין משימות נשלחו עדיין',
  // 'fullName': 'שם מלא',
  'enterFullName': 'הזן את שמך המלא',
  'firstName': 'שם פרטי',
  'enterFirstName': 'הזן את שמך הפרטי',
  'lastName': 'שם משפחה',
  'enterLastName': 'הזן את שם המשפחה שלך',
  'enterEmail': 'הזן את כתובת האימייל שלך',
  'companyName': 'שם החברה',
  'enterCompanyName': 'הזן את שם החברה שלך',
  'continue': 'המשך',
  'uploadAPuzzle': 'העלה חידה',
  'enrollment': 'הרשמה',

  // Validation Messages
  'mobileNumberRequired': 'מספר טלפון נדרש',
  'invalidPhoneNumber': 'מספר טלפון לא חוקי. חייב להיות לפחות 10 ספרות',
  'checking': 'בודק...',
  'generatingOtp': 'יוצר OTP...',
  'otpSent': 'OTP נשלח. שלח שוב ב',
  'seconds': 'שניות',
  'verifying': 'מאמת...',
  'submitting': 'שולח...',
  'fullNameRequired': 'שם מלא נדרש',
  'firstNameIsRequired': 'שם פרטי נדרש',
  'fullNameTooShort': 'שם מלא קצר מדי',
  'firstNameTooShort': 'שם פרטי קצר מדי',
  'lastNameRequired': 'שם משפחה נדרש',
  'lastNameIsRequired': 'שם משפחה נדרש',
  'lastNameTooShort': 'שם משפחה קצר מדי',
  'emailRequired': 'אימייל נדרש',
  'invalidEmail': 'כתובת אימייל לא חוקית',
  'totalPointsToWin': 'סה"כ נקודות לצבור',
  'totalPointsToWinRequired': 'סה"כ נקודות לצבור הוא שדה חובה',
  'totalPointsToWin(optional)': 'סה"כ נקודות לצבור (אופציונלי)',
  'pointsRequired': 'נקודות נדרשות',
  'isRequired': 'הוא שדה חובה',
  'companyNameRequired': 'שם חברה נדרש',
  'userNotFound': 'משתמש לא נמצא',
  'userAlreadySignedUp': 'משתמש כבר רשום',
  'waitForApproval': 'נא להמתין לאישור',
  'otpIncorrect': 'קוד אימות שגוי',
  'otpExpired': 'קוד אימות פג',
  'userNotAdmin': 'חשבון זה אינו חשבון מנהל',
  'userNotFoundPleaseSignUp': 'משתמש לא נמצא. אנא הירשם תחילה.',
  'accountPendingApproval': 'החשבון שלך ממתין לאישור מנהל.',
  'failedToGenerateVerificationCode': 'יצירת קוד האימות נכשלה',
  'failedToResendVerificationCode': 'שליחה מחדש של קוד האימות נכשלה',
  'failedToCreateAdminAccount': 'יצירת חשבון מנהל נכשלה',
  'genericErrorTryAgain': 'אירעה שגיאה. אנא נסה שוב.',
  'otpVerificationFailed': 'אימות קוד האימות נכשל',
  'errorWhileResendingCode': 'אירעה שגיאה בעת שליחת הקוד מחדש',

  // Promotions
  'promotions': 'הצעות',
  'createPromotion': 'צור הצעה',
  'updatePromotion': 'עדכן הצעה',
  'editPromotion': 'ערוך הצעה',
  'thisPromotion': 'ההצעה הזו',
  'titleRequired': 'כותרת היא שדה חובה',
  'titleMaxLengthExceeded': 'כותרת לא יכולה לעלות על 50 תווים',
  'backgroundImageRequired': 'תמונת רקע היא שדה חובה',
  'failedToCreatePromotion': 'יצירת הצעה נכשלה',
  'failedToUpdatePromotion': 'עדכון הצעה נכשל',
  'failedToDeletePromotion': 'מחיקת הצעה נכשלה',
  'frequency': 'תדירות',
  'daily': 'יומי',
  'oneTime': 'פעם אחת',
  'setInterval': 'הגדר מרווח',
  'selectInterval': 'בחר מרווח',
  'interval': 'מרווח',
  'days': 'ימים',
  'day': 'יום',
  // 'hours': 'שעות',
  'hour': 'שעה',
  'minutes': 'דקות',
  'minute': 'דקה',
  'intervalRequired': 'מרווח הוא שדה חובה',
  'allFieldsAreRequired': 'כל השדות הם שדות חובה',
  'zoomLinkIsRequired': 'קישור זום הוא שדה חובה',
  'pleaseEnterAValidURL': 'אנא הזן כתובת אימייל תקינה',
  'workshopDateIsRequired': 'תאריך הסדנה הוא שדה חובה',
  'startTimeIsRequired': 'שעת ההתחלה היא שדה חובה',
  'endTimeIsRequired': 'שעת הסיום היא שדה חובה',
  'nameOfWorkshopIsRequired': 'שם הסדנה הוא שדה חובה',
  'academyVODCreatedSuccessfully': 'ווידאו נוצר בהצלחה',
  'failedToCreateVOD': 'יצירת ווידאו נכשלה',
  'missionChallengeCreatedSuccessfully': 'משימה נוצרה בהצלחה',
  'option1CannotBeEmpty': 'אופציה 1 לא יכולה להיות ריקה',
  'option2CannotBeEmpty': 'אופציה 2 לא יכולה להיות ריקה',
  'option3CannotBeEmpty': 'אופציה 3 לא יכולה להיות ריקה',
  'option4CannotBeEmpty': 'אופציה 4 לא יכולה להיות ריקה',
  'option5CannotBeEmpty': 'אופציה 5 לא יכולה להיות ריקה',
  'option6CannotBeEmpty': 'אופציה 6 לא יכולה להיות ריקה',
  'option7CannotBeEmpty': 'אופציה 7 לא יכולה להיות ריקה',
  'option8CannotBeEmpty': 'אופציה 8 לא יכולה להיות ריקה',
  'option9CannotBeEmpty': 'אופציה 9 לא יכולה להיות ריקה',
  'option10CannotBeEmpty': 'אופציה 10 לא יכולה להיות ריקה',
  'correctAnswerIsRequired': 'תשובה נכונה היא שדה חובה',
  'taskStartDateIsRequired': 'תאריך התחלת המשימה הוא שדה חובה',
  'missionNameIsRequired': 'שם המשימה הוא שדה חובה',
  'missionEndTimeIsRequired': 'שעת סיום המשימה הוא שדה חובה',
  'zoomWorkshopCreatedSuccessfully': 'סדנה זום נוצרה בהצלחה',
  'failedToCreateZoomWorkshop': 'יצירת סדנה זום נכשלה',
  'vodNameIsRequired': 'שם הווידאו הוא שדה חובה',
  'videoFileIsRequired': 'קובץ הווידאו הוא שדה חובה',
  'invalidPoints': 'נקודות לא חוקיות',
  'update': 'עדכן',
  'editThisPost': 'ערוך את הפוסט',
};
